version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # This ensures code changes reflect immediately in the container
    ports:
      - "8000:8000"  # Expose port 8000 for Django development server
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name

volumes:
  postgres_data:
